# Generated by Django 4.2.1 on 2024-02-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('account_name', models.CharField(max_length=128)),
                ('account_bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('post_title', models.CharField(max_length=128)),
                ('post_community', models.CharField(max_length=128)),
                ('post_body', models.TextField()),
                ('post_tags', models.CharField(choices=[('RF', 'Risk Factions'), ('HD', 'Hell Divers'), ('C', 'Chess'), ('MTG', 'Magic The Gathering'), ('COD', 'Call Of Duty')], default='COD', max_length=50)),
            ],
        ),
    ]
