# Generated by Django 4.2 on 2024-04-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='reported_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='reported_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
