# Generated by Django 5.0.3 on 2024-03-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="password",
            field=models.CharField(default="password", max_length=64),
        )
    ]
