# Generated by Django 4.2.11 on 2024-08-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='event_status',
            field=models.CharField(choices=[('EC', 'Event has been Closed'), ('O', 'Open to Registration'), ('RC', 'Closed to Registration')], default='O', max_length=2),
        ),
    ]
