# Generated by Django 4.2 on 2024-03-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_tag_remove_post_post_tags_post_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default='password', max_length=64),
        ),
    ]
