# Generated by Django 4.2 on 2024-04-09 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='accountname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.account'),
        ),
    ]
