# Generated by Django 4.2 on 2024-07-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_eventpost_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='event_status',
            field=models.CharField(choices=[('O', 'Open to Registration'), ('EC', 'Event has been Closed'), ('RC', 'Closed to Registration')], default='O', max_length=2),
        ),
    ]
