# Generated by Django 4.2.1 on 2024-07-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_eventpost_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='event_status',
            field=models.CharField(choices=[('O', 'Open to Registration'), ('RC', 'Closed to Registration'), ('EC', 'Event has been Closed')], default='O', max_length=2),
        ),
    ]
